-- Sprint 1 intentionally has no fake production users or rooms.
-- Create a permanent organizer in Supabase Auth (email/password) for development.
-- Anonymous guest users are created only by the real /r/{join_code} flow.
